// Mocks generated by Mockito 5.4.0 from annotations
// in sports_app/test/features/scores/presentation/bloc/scores_bloc_tets.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i11;
import 'dart:typed_data' as _i12;

import 'package:dartz/dartz.dart' as _i4;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sports_app/core/error/failure.dart' as _i8;
import 'package:sports_app/core/network/network_info.dart' as _i3;
import 'package:sports_app/features/scores/data/datasources/scores_remote_data_source.dart'
    as _i2;
import 'package:sports_app/features/scores/data/repositories/scores_repository_impl.dart'
    as _i6;
import 'package:sports_app/features/scores/domain/entities/scores.dart' as _i9;
import 'package:sports_app/features/scores/domain/entities/sport.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScoresRemoteDataSourceImpl_0 extends _i1.SmartFake
    implements _i2.ScoresRemoteDataSourceImpl {
  _FakeScoresRemoteDataSourceImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkInfo_1 extends _i1.SmartFake implements _i3.NetworkInfo {
  _FakeNetworkInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScoresRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockScoresRepositoryImpl extends _i1.Mock
    implements _i6.ScoresRepositoryImpl {
  @override
  _i2.ScoresRemoteDataSourceImpl get remote => (super.noSuchMethod(
        Invocation.getter(#remote),
        returnValue: _FakeScoresRemoteDataSourceImpl_0(
          this,
          Invocation.getter(#remote),
        ),
        returnValueForMissingStub: _FakeScoresRemoteDataSourceImpl_0(
          this,
          Invocation.getter(#remote),
        ),
      ) as _i2.ScoresRemoteDataSourceImpl);
  @override
  _i3.NetworkInfo get network => (super.noSuchMethod(
        Invocation.getter(#network),
        returnValue: _FakeNetworkInfo_1(
          this,
          Invocation.getter(#network),
        ),
        returnValueForMissingStub: _FakeNetworkInfo_1(
          this,
          Invocation.getter(#network),
        ),
      ) as _i3.NetworkInfo);
  @override
  _i7.Future<_i4.Either<_i8.Failure, List<_i9.Scores>>> getScoresBySportKey(
          String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresBySportKey,
          [key],
        ),
        returnValue:
            _i7.Future<_i4.Either<_i8.Failure, List<_i9.Scores>>>.value(
                _FakeEither_2<_i8.Failure, List<_i9.Scores>>(
          this,
          Invocation.method(
            #getScoresBySportKey,
            [key],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i4.Either<_i8.Failure, List<_i9.Scores>>>.value(
                _FakeEither_2<_i8.Failure, List<_i9.Scores>>(
          this,
          Invocation.method(
            #getScoresBySportKey,
            [key],
          ),
        )),
      ) as _i7.Future<_i4.Either<_i8.Failure, List<_i9.Scores>>>);
  @override
  _i7.Future<_i4.Either<_i8.Failure, List<_i10.Sport>>> getSportsList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSportsList,
          [],
        ),
        returnValue:
            _i7.Future<_i4.Either<_i8.Failure, List<_i10.Sport>>>.value(
                _FakeEither_2<_i8.Failure, List<_i10.Sport>>(
          this,
          Invocation.method(
            #getSportsList,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i4.Either<_i8.Failure, List<_i10.Sport>>>.value(
                _FakeEither_2<_i8.Failure, List<_i10.Sport>>(
          this,
          Invocation.method(
            #getSportsList,
            [],
          ),
        )),
      ) as _i7.Future<_i4.Either<_i8.Failure, List<_i10.Sport>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i5.Client {
  @override
  _i7.Future<_i5.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i11.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response>);
  @override
  _i7.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<String>.value(''),
        returnValueForMissingStub: _i7.Future<String>.value(''),
      ) as _i7.Future<String>);
  @override
  _i7.Future<_i12.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
        returnValueForMissingStub:
            _i7.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
      ) as _i7.Future<_i12.Uint8List>);
  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i7.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
