// Mocks generated by Mockito 5.4.0 from annotations
// in sports_app/test/features/scores/domain/usecase/get_sports_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sports_app/core/error/failure.dart' as _i5;
import 'package:sports_app/features/scores/domain/entities/scores.dart' as _i7;
import 'package:sports_app/features/scores/domain/entities/sport.dart' as _i6;
import 'package:sports_app/features/scores/domain/repositories/scores_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScoresRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScoresRepository extends _i1.Mock implements _i3.ScoresRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Sport>>> getSportsList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSportsList,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Sport>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Sport>>(
          this,
          Invocation.method(
            #getSportsList,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Sport>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Sport>>(
          this,
          Invocation.method(
            #getSportsList,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Sport>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Scores>>> getScoresBySportKey(
          String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScoresBySportKey,
          [key],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.Scores>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Scores>>(
          this,
          Invocation.method(
            #getScoresBySportKey,
            [key],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.Scores>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Scores>>(
          this,
          Invocation.method(
            #getScoresBySportKey,
            [key],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Scores>>>);
}
